# Generated by Django 5.1.4 on 2025-01-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='customer',
        ),
    ]
